### ISSUE TITLE
Integration --> Gravatar Integration

### ISSUE THREAD

**Issue by akkassingh** [akkassingh/Ideaflow#4]

**Comment by pweetymega** [comment]
OBSERVATIONS
•	I observed that I can only attach a file from my profile, it will be easier to create a column at the submission page to attach the particular proposal.
•	A summary/abstract of the project should be shown at the proposal details
•	Funding type should have a drop-down with a list like partly funded, fully funded, scholarships, self-sponsorship, etc.
•	The mobile view is working perfectly, I was able to register and login using my mobile device and Pc.
•	I don’t know how to test for both internal users and external users, are we viewing automatically as an internal user or external user? Do we have to have a column for Admin to differentiate?
•	Can the Admin approve some proposals and also reject some proposals to make it easier for us to know if it is functioning well.
•	0.5MB of a file size is too small for a project proposal or can I get clarity on what we are to submit here
•	I selected a PNG  file that is small and it rejected it with this error message “Must supply api_key”
•	Should we add a helpline or a contact us at the buttom of the page or at the top left of the page with the other drop downs.
•	I like that a user can change the view to either dark or light.
•	We should have a notification/alert buttons that will alert us of any changes in our proposals.
